### ISSUE TITLE
Cannot open p12

### ISSUE THREAD

**Issue by shaneheyworth** [OzanKurt/google-analytics#6]
file_get_contents(storage/BlacktieCorridor-b9cb822de1b7.p12): failed to open stream: No such file or directory

I've tried the following:
php artisan cache:clear 

chmod -R 777 storage 

composer dump-autoload

Any ideas why this wouldn't work? I'm following your documentation.

**Comment by OzanKurt** [comment]
This is probably because your system cannot find the file. Can you please double check if the file is in the right directory and send me a screenshot?

**Comment by shaneheyworth** [comment]
It is. I even tried it in public. I tried chmodding the storage folder.
Attached is a screenshot.

**Comment by shaneheyworth** [comment]
![screen shot 2016-02-10 at 1 39 33 am](https://cloud.githubusercontent.com/assets/16281266/12940458/4b6bdd4a-cf97-11e5-9ad0-c27ee9806675.png)
<img width="903" alt="screen shot 2016-02-10 at 1 40 03 am" src="https://cloud.githubusercontent.com/assets/16281266/12940459/4b7669f4-cf97-11e5-899b-4d94ec8f046a.png">

**Comment by OzanKurt** [comment]
Can you please try `storege_path('BlacktieCorridor-b9cb822de1b7.p12')`?

**Comment by shaneheyworth** [comment]
Thank you. This worked. You should update your google.php config file to
note this :)

**Comment by OzanKurt** [comment]
Great!

I will add that as a note, thanks. ;)

Hope my package helped.

**Comment by shaneheyworth** [comment]
It has. Thank you for building it.

You should also note that those who have a BaseWebController need to
place parent::__construct(); in the constructor!

**Comment by shaneheyworth** [comment]
Two more things:
- You should make mention that you need to add the analytics
  'serviceAccountName' that you reference as a user in the Google Analytics
  side of things under User Management. It will give you a 403 error
  otherwise.
- You should also note what other items are available to be grabbed using
  your API beyond Users and Page Views :)

**Comment by shaneheyworth** [comment]
I'm attempting to use execute to grab my sessions as per your src code:

$results = $this->ga->execute(['ga:sessions'])->parseResults();

gives me this:

Property [0] does not exits.

Am I missing something here? I know documentation is annoying but kind of
frustrating lol

**Comment by OzanKurt** [comment]
It has been a bit since I last checked the code, I will soon have a look and update. Make sure you watch the repo for incoming changes.

**Comment by shaneheyworth** [comment]
I got around it. But thank you! It's appreciated :) It's a good package
otherwise
