### ISSUE TITLE
Class 'Kurt\Google\Analytics\Exceptions\InvalidPeriodException' not found

### ISSUE THREAD

**Issue by baddwin** [OzanKurt/google-analytics#8]
```
in Period.php line 95
at Period->validatePeriod(object(Carbon), object(Carbon)) in Period.php line 77
at Period->setEndDate(object(Carbon)) in DatesHandler.php line 51
at Analytics->setEndDate(object(Carbon)) in AdminController.php line 43
at AdminController->__construct(object(Analytics))
at ReflectionClass->newInstanceArgs(array(object(Analytics))) in Container.php line 794
at Container->build('App\Http\Controllers\AdminController', array()) in Container.php line 644
at Container->make('App\Http\Controllers\AdminController', array()) in Application.php line 709
at Application->make('App\Http\Controllers\AdminController') in Route.php line 203
......
```

Hi, I tried to set `startDate` and `endDate` in cunstructor manually, but always ended up getting error above. But after I changed the code of `Period.php` at line 51 to this: `$this->validatePeriod(null, $startDate);` the error has gone. so what's going on there?

Edit: o yeah, I also got the result of API call like this.

![screenshot_20170127_095707](https://cloud.githubusercontent.com/assets/7449857/22359729/5db6250a-e47c-11e6-99a2-7d22db63c394.png)

Why the month numbers of December become `11` instead of `12` and for January also `00` instead of `01`?

**Comment by OzanKurt** [comment]
1- Can you please provide which dates you entered to the constructor?

2- Sadly, the google analytics API returns the months starting from 0. It's confusing but it's how it is. ✌️

**Comment by baddwin** [comment]
```
private $ga;

    function __construct(GoogleAnalytics $ga) {
        $this->middleware('auth');
        $this->ga = $ga;
        $ga->setStartDate(Carbon::parse('7 days ago'));
        $ga->setEndDate(Carbon::parse('yesterday'));
    }
```
is it what you meant?

**Comment by OzanKurt** [comment]
Yes thanks, your input is correct, I will check where the problem is and return as soon as possible. 

Thanks.

Ozan Kurt

**Comment by baddwin** [comment]
o yeah, I forgot to mention that I'm in Laravel 5.3

**Comment by OzanKurt** [comment]
Are you sure that the carbon objects are giving you the expected results?

**Comment by baddwin** [comment]
I'm rather confused though, but that's what I get

**Comment by baddwin** [comment]
So, what should I do?
And how should I parse google API return data of `Date(2017, 00, 01)` in PHP, for instance?

**Comment by OzanKurt** [comment]
You can simply do `+1`.

**Comment by baddwin** [comment]
OK, thank you

**Comment by baddwin** [comment]
Wait, I didn't notice the last hotfix. As soon as I found it yesterday, I updated the package to it, but my issue still persist before I change line 51 of `Period.php`

**Comment by OzanKurt** [comment]
You should be getting an Exception as expected. Can you show me the error message?

**Comment by baddwin** [comment]
Okay, I got it that date response value like `Date(2017, 00, 01)` is likely intended to be parsed for Javascript's Date method.

As for the error message I got, it's likely triggered by `setStartDate` and `setEndDate` method of `$ga` instance. So, please just tell me or give me an example how to set start and end date of the analytics data that I want.

**Comment by baddwin** [comment]
Please help I still don't get it to set start date and end date.
I just want to get analytics for past week.

Edit: solved.
